---
# tasks file for netdatarole

- include_tasks: uninstall_netdata.yml
  when: remove_existing_install == true 

- include_tasks: create_netdata_group_and_user.yml

- include_tasks: download_and_install_netdata.yml

- include_tasks: configure_netdata.yml

- include_tasks: configure_apache_weblog.yml
  when: apache_log_format is defined

- include_tasks: configure_netdata_collectors.yml
  when: configure_netdata_collectors == true

- include_tasks: reset_collectors.yml
  when: configure_netdata_collectors == false